### ISSUE TITLE
Cannot get to run on Windows 10

### ISSUE THREAD

**Issue by orinwalker** [digitalocean/nginxconfig.io#338]
## Information
https://whatismybrowser.com/w/384LKK4

### Problem
Getting error when trying to build:

Fetching Community Tools template from www.digitalocean.com...
...fetching & conversion completed, saved to build/base.html

> nginxconfig.io@1.0.0 build:prism D:\IaaProjects\Sandbox\Nginx\nginxconfig.io
> node src/nginxconfig/build/prism.js

> nginxconfig.io@1.0.0 build:static D:\IaaProjects\Sandbox\Nginx\nginxconfig.io
> copyfiles --up 2 src/static/{*,**/*} dist

> nginxconfig.io@1.0.0 build:tool D:\IaaProjects\Sandbox\Nginx\nginxconfig.io
> vue-cli-service build src/nginxconfig/mount.js --no-clean

 ERROR  Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'd:'
Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'd:'
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:791:11)
    at Loader.resolve (internal/modules/esm/loader.js:89:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:242:28)
    at Loader.import (internal/modules/esm/loader.js:177:28)
    at importModuleDynamically (internal/modules/cjs/loader.js:1015:27)
    at exports.importModuleDynamicallyCallback (internal/process/esm_loader.js:30:14)
    at loadFileConfig (D:\IaaProjects\Sandbox\Nginx\nginxconfig.io\node_modules\@vue\cli-service\lib\util\loadFileConfig.js:28:7)
    at Service.loadUserOptions (D:\IaaProjects\Sandbox\Nginx\nginxconfig.io\node_modules\@vue\cli-service\lib\Service.js:323:44)
    at Service.init (D:\IaaProjects\Sandbox\Nginx\nginxconfig.io\node_modules\@vue\cli-service\lib\Service.js:73:30)
    at Service.run (D:\IaaProjects\Sandbox\Nginx\nginxconfig.io\node_modules\@vue\cli-service\lib\Service.js:231:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nginxconfig.io@1.0.0 build:tool: `vue-cli-service build src/nginxconfig/mount.js --no-clean`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nginxconfig.io@1.0.0 build:tool script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\orinw_t1xyplb\AppData\Roaming\npm-cache\_logs\2022-03-15T13_30_10_213Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nginxconfig.io@1.0.0 build: `npm run build:clean && npm run build:template && npm run build:prism && npm run build:static && npm run build:tool`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nginxconfig.io@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\orinw_t1xyplb\AppData\Roaming\npm-cache\_logs\2022-03-15T13_30_10_239Z-debug.log

### What I have tried
Tried running in Git Bash, Powershell, and Ubuntu 20.04 using WSL2. All of these give the same error. Have tried cloning to a fresh folder, but get the same error. 

### Screenshots
N/A

Thank you!

**Comment by MattIPv4** [comment]
👀 This sounds like an issue w/ vue-cli-service itself

**Comment by orinwalker** [comment]
Not sure how to fix it

**Comment by MattIPv4** [comment]
👋 We updated a load of dependencies a few weeks ago as part of the migration to Vue 3. Would you be able to try again?

**Comment by zhou431615** [comment]
> 👀 This sounds like an issue w/ vue-cli-service itself



> Not sure how to fix it

Have you solved it now?

**Comment by kristekw** [comment]
got same issue with current version

> 👋 We updated a load of dependencies a few weeks ago as part of the migration to Vue 3. Would you be able to try again?

i got the same issue with current version which the dependencies includes "vue": "^3.2.31"

**Comment by 24min** [comment]
got Same issue...
My node version is **v16.14.2**
![3d51fda70d565deae118ff7f6b52904](https://user-images.githubusercontent.com/32154293/166131021-f3bc1452-cc19-4897-a378-386eac472f99.png)

**Comment by MattIPv4** [comment]
I don't have a Windows device setup that I can debug this on unfortunately, so I'll leave this issue open to the community for anyone that wishes to dive in and look at resolving this :)

**Comment by CChiaki** [comment]
On Windows 10  
I chang to edit 
/Users/cchiaki/代码/HBuilderProjects/nginxconfig.io-master/node_modules/@vue/cli-service/lib/util/loadFileConfig.js

like this  

![image](https://user-images.githubusercontent.com/3146450/169189704-6be12cd3-83d9-4ddc-8053-34bac40a189f.png)

It is Ok；

error log:
Import("D://cchiaki/代码/HBuilderProjects/nginxconfig.io-master/vue.config.js")
On Windows, absolute paths must be valid file:// URLs. Received protocol 'd:'
